"""Contract Update

Revision ID: 5f9725129e1b
Revises: f432adbc308e
Create Date: 2026-06-25 21:19:11.931133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f9725129e1b'
down_revision: Union[str, Sequence[str], None] = 'f432adbc308e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('charge_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'contract', ['charge_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='unique')
    op.drop_column('contract', 'charge_id')
    # ### end Alembic commands ###
