"""Typing fix

Revision ID: 62fec24eb912
Revises: 5f9725129e1b
Create Date: 2026-06-25 23:39:28.550271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fec24eb912'
down_revision: Union[str, Sequence[str], None] = '5f9725129e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('refund_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('contract_refound_id_key'), 'contract', type_='unique')
    op.create_unique_constraint(None, 'contract', ['refund_id'])
    op.drop_column('contract', 'refound_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('refound_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contract', type_='unique')
    op.create_unique_constraint(op.f('contract_refound_id_key'), 'contract', ['refound_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('contract', 'refund_id')
    # ### end Alembic commands ###
