"""New Tables

Revision ID: 685f280f087a
Revises: faf8408d32af
Create Date: 2026-06-18 22:28:13.996543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685f280f087a'
down_revision: Union[str, Sequence[str], None] = 'faf8408d32af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'porfile_id', new_column_name='profile_id')
    op.create_table('abilitie',
    sa.Column('abilitie_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('abilitie_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=90), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('budget', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('abilities_profile',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('abilitie_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['abilitie_id'], ['abilitie.abilitie_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'abilitie_id', 'profile_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('porfile_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('profile', sa.Column('abilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profile', 'profile_id')
    op.drop_table('abilities_profile')
    op.drop_table('job')
    op.drop_table('abilitie')
    # ### end Alembic commands ###
