"""Applications Review

Revision ID: 6c028c70481e
Revises: 01880cbec719
Create Date: 2026-06-20 20:06:03.633266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c028c70481e'
down_revision: Union[str, Sequence[str], None] = '01880cbec719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('abilities_description', sa.String(), nullable=False))
    op.drop_column('application', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('application', 'abilities_description')
    # ### end Alembic commands ###
