"""Many to many

Revision ID: 73a7e66d1e78
Revises: 4419a4456726
Create Date: 2026-06-19 18:03:29.436327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a7e66d1e78'
down_revision: Union[str, Sequence[str], None] = '4419a4456726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities_job',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('abilitie_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['abilitie_id'], ['abilitie.abilitie_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ),
    sa.PrimaryKeyConstraint('job_id', 'abilitie_id')
    )
    op.drop_constraint(op.f('abilities_profile_job_id_fkey'), 'abilities_profile', type_='foreignkey')
    op.drop_column('abilities_profile', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abilities_profile', sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('abilities_profile_job_id_fkey'), 'abilities_profile', 'job', ['job_id'], ['job_id'])
    op.drop_table('abilities_job')
    # ### end Alembic commands ###
