"""Name chamged

Revision ID: ec8594e0a8e5
Revises: 1d5921549e34
Create Date: 2026-06-24 04:07:32.581297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8594e0a8e5'
down_revision: Union[str, Sequence[str], None] = '1d5921549e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('user_id_b', sa.String(), nullable=False))
    op.create_foreign_key(None, 'conversation', 'users', ['user_id_b'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation', type_='foreignkey')
    op.drop_column('conversation', 'user_id_b')
    # ### end Alembic commands ###
