"""Changes Revision

Revision ID: f7f8900e7b33
Revises: 685f280f087a
Create Date: 2026-06-18 22:40:53.761395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f8900e7b33'
down_revision: Union[str, Sequence[str], None] = '685f280f087a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'abilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('abilities', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
