"""First Commit

Revision ID: faf8408d32af
Revises: 
Create Date: 2026-06-17 16:10:27.227626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf8408d32af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', 'PROFESSIONAL', name='role_types'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('stripe_connect_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contract',
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('seller_id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'GUARANTEED', 'COMPLETED', 'REFOUNDED', 'FAILED', 'DISPUTED', name='contract types'), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_intent_id', sa.String(), nullable=True),
    sa.Column('transfer_id', sa.String(), nullable=True),
    sa.Column('refound_id', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('contract_id'),
    sa.UniqueConstraint('payment_intent_id'),
    sa.UniqueConstraint('refound_id'),
    sa.UniqueConstraint('transfer_id')
    )
    op.create_table('conversation',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id_a', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_a'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('profile',
    sa.Column('porfile_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('social_media', sa.String(), nullable=True),
    sa.Column('abilities', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('porfile_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('profile')
    op.drop_table('conversation')
    op.drop_table('contract')
    op.drop_table('users')
    # ### end Alembic commands ###
